# Generated by Django 3.2.18 on 2023-04-17 21:18

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_categories'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=128, unique=True),
        ),
    ]
