# Generated by Django 3.2.18 on 2023-04-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_info',
            field=models.JSONField(),
        ),
    ]
