# Generated by Django 3.2.18 on 2023-05-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230501_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_info',
        ),
    ]
