# Generated by Django 3.2.18 on 2023-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
